#!/bin/bash
# Generate a .env with fresh secrets for the Aegis compose stack.
#
# The stack refuses to start without these (docker-compose.yml uses the
# ${VAR:?} form) and the application refuses to start on the shipped
# development defaults (backend/app/security_posture.py). A security product
# that ships with a known HMAC key is not a convenience, so there is no
# fallback: generate real values once, here.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$ROOT/.env"

if [ -e "$TARGET" ] && [ "${1:-}" != "--force" ]; then
  echo "$TARGET already exists. Re-run with --force to replace it." >&2
  exit 1
fi

gen() { python3 -c "import secrets; print(secrets.token_urlsafe(32))"; }

cat > "$TARGET" <<ENV
# Generated by scripts/init-env.sh -- do not commit (.env is gitignored).
AEGIS_SECRET_KEY=$(gen)
AEGIS_EAT_KEY=$(gen)
AEGIS_EVIDENCE_SECRET_KEY=$(gen)
AEGIS_INTERNAL_GATEWAY_TOKEN=$(gen)
AEGIS_INTERNAL_TOOL_TOKEN=$(gen)
AEGIS_CRM_SECRET=$(gen)
ENV

chmod 600 "$TARGET"
echo "Wrote $TARGET with fresh secrets."
